name: Deploy React Front

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create new build
        run: npm install
          npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # - name: Connecting through ssh
      #   run: ssh -p 22 quickval@${{ secrets.SSH_HOST }}

      # - name: Creating Build
      #   run: cd public_html/trikaro
      #     git pull origin master
      #     npm run build
      #     cd ../../
      #     rsync -a public_html/trikaro/build/* public_html/
      #     cp public_html/trikaro/.htaccess public_html/.htaccess
