name: Deploy React Front

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create new build
        run: npm install
          npm run build
  deploy:
    name: Deploy On Server
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
      - with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connecting through ssh
      - run: ssh quickvil@quickvila.store

      - runs: cd /home/quickvil/public_html/trikaro
      - runs: git pull origin master
      - runs: npm run build
      - runs: rsync -a /home/quickvil/public_html/trikaro/build/* /home/quickvil/public_html/
      - runs: cp /home/quickvil/public_html/trikaro/.htaccess /home/quickvil/public_html/.htaccess
